### ISSUE TITLE
etcd operator needs cluster role binding

### ISSUE THREAD

**Issue by mjudeikis** [jim-minter/azure-helm#73]
If we say we want to run one operator per customer (one operator managed one etcd cluster) we will need to create ClusterRole and ClusterRoleBinding for that operator serviceaccount (or default one).

This implies we:
1. Will have cluster-admin kubeconfig to do so.
2. We will have to know namespace of HCP in the config when generating.

If we would run one global operator we still need same, but this would be one-time setup for all HCP cluster. Ideas?

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: etcd-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: etcd-operator
subjects:
- kind: ServiceAccount
  name: default
  namespace: "{{ .Config.Namespace }}"
```

assuming ClusterRole `etcd-operator` is created already.
